# Generated by Django 5.1.3 on 2024-11-24 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0004_remove_produto_quantidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
